## Numpy:- 
it is built in library given by python that is called numpy.<br>
it is applicable for numerical computing.

In [88]:
# ! pip install numpy

In [89]:
import numpy as np

In [90]:
print(dir(np)) # dir(library name) ye usss library ke sare function show kar dega.

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

#### Create single dimensional array:-

In [91]:
single_dim=np.array([1,2,3])
single_dim

array([1, 2, 3])

In [92]:
type(single_dim)

numpy.ndarray

In [93]:
single_dim.shape

(3,)

#### Shape(row,column)

In [94]:
mul_dim=np.array([[1,2,3],
                  [4,5,6]])

In [95]:
mul_dim.shape

(2, 3)

In [96]:
mul_dim=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [97]:
mul_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
mul_dim.shape

(3, 3)

In [99]:
mul_dim+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [100]:
mul_dim.shape

(3, 3)

In [101]:
single=np.array([1,2,3,4,5,6,7,8,9,2,4,6]).reshape(3,4)

In [102]:
single

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 2, 4, 6]])

In [103]:
single.shape

(3, 4)

Create the zeroes in arrays

v=vertical,h=horizontal,

In [104]:
arr1=np.array([10,20,30,40])
arr2=np.array([11,22,33,44])
print(arr1)
print(arr2)

[10 20 30 40]
[11 22 33 44]


In [105]:
# combine the two array
# adding the two array in three ways
# 1.vstack:-multidimensional array can be create
arr3=np.vstack((arr1,arr2))
print(arr3)
np.shape(arr3)

[[10 20 30 40]
 [11 22 33 44]]


(2, 4)

In [106]:
# 2.hstack:-create the singledimensional array
arr3=np.hstack((arr1,arr2))
print(arr3)
np.shape(arr3)

[10 20 30 40 11 22 33 44]


(8,)

In [107]:
#3.
# np.column_stack()

Numpy intersection and difference


In [108]:
arr1=np.array([10,20,30,40])
arr2=np.array([11,22,33,44,10,40])
comman=np.intersect1d(arr1,arr2) # intersection means comman element 
comman

array([10, 40])

In [109]:
difference=np.setdiff1d(arr1,arr2)
difference
# np.setdiff1d(arr2,arr1)

array([20, 30])

Numpy Array Mathematics

In [111]:
n1=np.array([10,20,3])
n2=np.array([30,40,10])
res=sum([n1,n2])
res

array([40, 60, 13])

In [114]:
n1=np.array([10,20,25])
n2=np.array([30,40,10])
res=np.sum([n1,n2],axis=1)# jo axis=1 columns ke liye or axis=0 rows ke liye hota h
res

array([55, 80])

Numpy Math Function

In [117]:
num=[23,11,33,22,87,94,14,79]
res=np.median(num)
print(res)

28.0


In [118]:
np.mean(num)

np.float64(45.375)

Numpy Save & Load

In [121]:
arr=np.array([10,20,30,40,50,60,70])
np.save('myarr',arr)

In [122]:
np.load('myarr.npy')

array([10, 20, 30, 40, 50, 60, 70])